//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btMVC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayGiat
    {
        public int Ma { get; set; }
        public string Ten { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string NhaSanXuat { get; set; }
    }
}
