//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btMVC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int Ma { get; set; }
        public string Hoten { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Quequan { get; set; }
        public Nullable<int> Luongcoban { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public string Dienthoai { get; set; }
    }
}
