//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btMVC3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string Ma { get; set; }
        public string Ten { get; set; }
        public Nullable<int> Giaban { get; set; }
        public Nullable<System.DateTime> Ngaynhap { get; set; }
        public Nullable<bool> Giamgia { get; set; }
        public string Mota { get; set; }
        public string Hinh { get; set; }
    }
}
